language: node_js

node_js:
  - "5.3"
  - "4.2"
  - "0.12"
  - "0.10"

before_install:
  - npm -g install npm@latest-2
  - echo "//registry.npmjs.org/:_authToken=\$NPM_TOKEN" > .npmrc

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true